# Generated by Django 5.0.1 on 2024-01-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0002_fipebrand_fipevehicletype_fipemodel_fipecodefipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fipeprice',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fipe_app.fipebrand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fipeprice',
            name='fuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fipe_app.fipefuel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fipeprice',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fipe_app.fipeyear'),
            preserve_default=False,
        ),
    ]
