# Generated by Django 5.0.1 on 2024-01-04 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0003_fipeprice_brand_fipeprice_fuel_fipeprice_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fipe_app.fipefuel'),
        ),
    ]
