# Generated by Django 5.0.1 on 2024-01-05 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0004_alter_lead_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fipe_app.fipeyear'),
        ),
    ]
