# Generated by Django 5.0.1 on 2024-01-06 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0009_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fipe_app.company'),
        ),
    ]
