# Generated by Django 5.0.1 on 2024-01-08 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0013_alter_perfil_managers_remove_perfil_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='perfil',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='password',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='username',
        ),
    ]
