# Generated by Django 5.0.1 on 2024-01-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0016_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
