# Generated by Django 5.0.1 on 2024-01-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0018_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='company',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='state',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
