# Generated by Django 5.0.1 on 2024-02-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0020_delete_fipedata_alter_lead_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='categoria_carro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='categoria_mercado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
