# Generated by Django 5.0.1 on 2024-02-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0021_lead_categoria_carro_lead_categoria_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='porcentagem_precificacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
