# Generated by Django 5.0.1 on 2024-02-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0022_lead_original_price_lead_porcentagem_precificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='categoria_carro',
            new_name='car_category',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='categoria_mercado',
            new_name='market_category',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='porcentagem_precificacao',
            new_name='pricing_percentage',
        ),
    ]
