# Generated by Django 5.0.1 on 2024-03-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0024_lead_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='vehicle_type',
        ),
    ]
