# Generated by Django 5.0.1 on 2024-03-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0026_lead_city_lead_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='fipebrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands_images/'),
        ),
    ]
