# Generated by Django 5.0.1 on 2024-03-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0027_remove_lead_city_remove_lead_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='revisions_done_in_css',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='under_warranty',
            field=models.BooleanField(default=False),
        ),
    ]
