# Generated by Django 5.0.3 on 2024-03-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0029_auto_20240312_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='fipebrand',
            name='show_in_template',
            field=models.BooleanField(default=False),
        ),
    ]
