# Generated by Django 3.2.13 on 2024-09-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_app', '0030_fipebrand_show_in_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fipecodefipe',
            name='model',
        ),
        migrations.RemoveField(
            model_name='fipefuel',
            name='year',
        ),
        migrations.RemoveField(
            model_name='fipemodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='fipemodel',
            name='version',
        ),
        migrations.RemoveField(
            model_name='fipeprice',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='fipeprice',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='fipeprice',
            name='model',
        ),
        migrations.RemoveField(
            model_name='fipeprice',
            name='year',
        ),
        migrations.RemoveField(
            model_name='fipeversion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='fipeyear',
            name='model',
        ),
        migrations.AlterField(
            model_name='lead',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fuel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='year',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='FipeBrand',
        ),
        migrations.DeleteModel(
            name='FipeCodeFipe',
        ),
        migrations.DeleteModel(
            name='FipeFuel',
        ),
        migrations.DeleteModel(
            name='FipeModel',
        ),
        migrations.DeleteModel(
            name='FipePrice',
        ),
        migrations.DeleteModel(
            name='FipeVehicleType',
        ),
        migrations.DeleteModel(
            name='FipeVersion',
        ),
        migrations.DeleteModel(
            name='FipeYear',
        ),
    ]
